# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import inference_pb2 as inference__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in inference_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InferenceStub:
    """Inference service provides workspace-scoped inference route configuration and bundle delivery.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetInferenceBundle = channel.unary_unary(
                '/openshell.inference.v1.Inference/GetInferenceBundle',
                request_serializer=inference__pb2.GetInferenceBundleRequest.SerializeToString,
                response_deserializer=inference__pb2.GetInferenceBundleResponse.FromString,
                _registered_method=True)
        self.SetInferenceRoute = channel.unary_unary(
                '/openshell.inference.v1.Inference/SetInferenceRoute',
                request_serializer=inference__pb2.SetInferenceRouteRequest.SerializeToString,
                response_deserializer=inference__pb2.SetInferenceRouteResponse.FromString,
                _registered_method=True)
        self.GetInferenceRoute = channel.unary_unary(
                '/openshell.inference.v1.Inference/GetInferenceRoute',
                request_serializer=inference__pb2.GetInferenceRouteRequest.SerializeToString,
                response_deserializer=inference__pb2.GetInferenceRouteResponse.FromString,
                _registered_method=True)
        self.DeleteInferenceRoute = channel.unary_unary(
                '/openshell.inference.v1.Inference/DeleteInferenceRoute',
                request_serializer=inference__pb2.DeleteInferenceRouteRequest.SerializeToString,
                response_deserializer=inference__pb2.DeleteInferenceRouteResponse.FromString,
                _registered_method=True)


class InferenceServicer:
    """Inference service provides workspace-scoped inference route configuration and bundle delivery.
    """

    def GetInferenceBundle(self, request, context):
        """Return the resolved inference route bundle for sandbox-local execution.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetInferenceRoute(self, request, context):
        """Set the inference route for a workspace.

        This controls how requests sent to `inference.local` are routed
        for sandboxes in the specified workspace.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInferenceRoute(self, request, context):
        """Get the inference route for a workspace.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteInferenceRoute(self, request, context):
        """Delete an inference route from a workspace.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetInferenceBundle': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInferenceBundle,
                    request_deserializer=inference__pb2.GetInferenceBundleRequest.FromString,
                    response_serializer=inference__pb2.GetInferenceBundleResponse.SerializeToString,
            ),
            'SetInferenceRoute': grpc.unary_unary_rpc_method_handler(
                    servicer.SetInferenceRoute,
                    request_deserializer=inference__pb2.SetInferenceRouteRequest.FromString,
                    response_serializer=inference__pb2.SetInferenceRouteResponse.SerializeToString,
            ),
            'GetInferenceRoute': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInferenceRoute,
                    request_deserializer=inference__pb2.GetInferenceRouteRequest.FromString,
                    response_serializer=inference__pb2.GetInferenceRouteResponse.SerializeToString,
            ),
            'DeleteInferenceRoute': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteInferenceRoute,
                    request_deserializer=inference__pb2.DeleteInferenceRouteRequest.FromString,
                    response_serializer=inference__pb2.DeleteInferenceRouteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'openshell.inference.v1.Inference', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('openshell.inference.v1.Inference', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Inference:
    """Inference service provides workspace-scoped inference route configuration and bundle delivery.
    """

    @staticmethod
    def GetInferenceBundle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openshell.inference.v1.Inference/GetInferenceBundle',
            inference__pb2.GetInferenceBundleRequest.SerializeToString,
            inference__pb2.GetInferenceBundleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetInferenceRoute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openshell.inference.v1.Inference/SetInferenceRoute',
            inference__pb2.SetInferenceRouteRequest.SerializeToString,
            inference__pb2.SetInferenceRouteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInferenceRoute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openshell.inference.v1.Inference/GetInferenceRoute',
            inference__pb2.GetInferenceRouteRequest.SerializeToString,
            inference__pb2.GetInferenceRouteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteInferenceRoute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openshell.inference.v1.Inference/DeleteInferenceRoute',
            inference__pb2.DeleteInferenceRouteRequest.SerializeToString,
            inference__pb2.DeleteInferenceRouteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
